### ISSUE TITLE
Send SMS to recipient with secure link to delivery page (map with courier location) when pickup is registered

### ISSUE THREAD

**Issue by johan-fvh** [ForumViriumHelsinki/CityLogistics#16]

**Comment by juhanikantola** [comment]
Do you need an SMS gateway for this? Let me know if you do, I can set you up with our corporate SMS gateway if you do.

**Comment by johan-fvh** [comment]
> Do you need an SMS gateway for this? Let me know if you do, I can set you up with our corporate SMS gateway if you do.

@juhanikantola Yes! The current implementation uses Twilio, which provides some free messages initially for testing, but if FVH is using another service with a Python/ReST API I could switch?

**Comment by juhanikantola** [comment]
Okay! I've used GatewayAPI.com, which has everything you need and has been quite solid (compared to let's say ClickSend). I've sent you an invite so you can create an API key etc. Let me know how much credits are needed eventually (some estimate).

**Comment by johan-fvh** [comment]
Hmm, messages appear to be 2c; 1000 messages would be 20e. The only planned use for this system is demoing, that should be plenty for that purpose. May be we'll never reach 100.

**Comment by juhanikantola** [comment]
Sounds good! Okay, just let me know if the account needs a refill.
